### ISSUE TITLE
ESP32 key v1.0 not working after removing legacy discovery

### ISSUE THREAD

**Issue by Nemnich** [NicoIIT/esphome-ble_adv_proxy#16]
USB dongle not found after removing legacy discovery. I don't know what's wrong, but my ESP32 key v1.0 suddenly doesn't work with integration. The firmware is 2025.9.3. So should I buy a newer ESP32 device, or upload something else to it? I don't know where to look, or maybe support for this device has ended?

**Comment by NicoIIT** [comment]
> the ha-ble-adv integration, which stopped working

Fine. It stopped working on your side. On my side it works perfectly, and same for 99% of the users probably. If you want to know why it is not working on your side you will have to provide info...

> after removing the legacy mode

Please stop saying that... The correct wording is "After rebuild with last version". If you do not understand the last commit message, do not use it...

So now let's try to do PROPERLY what you have not done, which is answering to questions:

* have you done something? YES, I rebuild and uploaded the firmware of my ESP32
* what was the previous conditions on which it worked? The last build done around the xx/yy/2025 was working
* Have you tried to put it back in those conditions? NO, because I do not know how to do that
```
external_components:
  - source: github://NicoIIT/esphome-ble_adv_proxy#123f254  # The previous commit before the change you _think_ is problematic
```

* does it compile? YES
* starts? YES
* connects to HA? YES 
* is properly discovered by HA? the Bluetooth_proxy part is properly discovered by HA as I have a sensor working with it, I do not know for the `ble_adv_proxy` part

* do you mean ha-ble-adv integration? YES
* which version? **THE MOST IMPORTANT QUESTION AND NO ANSWER**
* diagnostic dump? I do not know where to find this info. 
     => https://www.home-assistant.io/integrations/diagnostics/

So please answer the non answered questions.

**Comment by Nemnich** [comment]
The last working build was before firmware version 2025.9.2, I don't know what version of this add-on was, but I'll try the previous one.
The last time it worked was the day before yesterday before 18:00. I remember that in the HA log there were some records about legacy something from HA BLE adv, but I didn't pay much attention to it, because I probably have the latest version.
Now I'm completely lost, because I did several restores from Home Assistant backups and completely lost track of what was happening. 😪 Unfortunately, with the current firmware uploaded, the device is ignored even by older versions of HA BLE adv.

**Comment by NicoIIT** [comment]
1. INTEGRATION DIAGNOSTIC DUMP (3RD TIME I REQUEST IT)
2. INTEGRATION DIAGNOSTIC DUMP (3RD TIME I REQUEST IT)
3. INTEGRATION DIAGNOSTIC DUMP (3RD TIME I REQUEST IT)

**Comment by Nemnich** [comment]
I can't get an integration diagnostic dump because I deleted the existing settings and ha-ble-adv doesn't show up in the integrations. When I am trying to add the BLe ADV Ceiling Fan / Lamps integration, it says No Bluetooth devices found. I'm quitting.
Please check the Troubleshooting Guide - Step 1.2.

**Comment by NicoIIT** [comment]
Wooo... You can find this info in Home Assistant doc.
I will do a new version tomorrow to allow you to download a diagnostic dump directly from the config flow when you see the "no adapter found" error.

In the meanwhile, you can try the good old delete/add:
* Delete your ESPHome node in Home assistant
* Restart HA
* Add again the ESPHome node

Sometimes it works... Sometimes a simple HA restart also works.

**Comment by NicoIIT** [comment]
OK, so with this restore it is not working because:
* in this dump we can see the adapter_name setup for the integration is `esp32-bluetooth-proxy-2ded8c`
* BUT in the esp yaml config you provided you setup `adapter_name: esp-proxy`, with the consequences written in the comments just above: your integration is no more working....

Now this does not explain why with latest version you have no adapter discovered. For that I published new version v1.4.1 with added diagnostics in the config flow, and logs in adapter creation:
1. Upgrade to version v1.4.1
2. Restart HA
3. Refresh your browser cache (Ctrl + F5 usually)
4. Retry to add a device. If no adapter is detected you will have the choice to open an issue, and clicking on it you will have the possibility to download the diagnostic dump containing the info I added to diagnose your issue.

**Comment by Nemnich** [comment]
Unfortunately, the adapter still can't find it... I suggest we both take a break and tackle this tomorrow, or another time. Let's not go all night.

[ble_adv_diag.json](https://github.com/user-attachments/files/22671277/ble_adv_diag.json)

**Comment by Nemnich** [comment]
[
  "sensor.esphome_device_builder_verze",
  "sensor.esphome_device_builder_nejnovejsi_verze",
  "sensor.esphome_device_builder_procento_cpu",
  "sensor.esphome_device_builder_procento_pameti",
  "sensor.backup_stav_spravce_zalohovani",
  "sensor.backup_dalsi_planovane_automaticke_zalohovani",
  "sensor.backup_posledni_uspesne_automaticke_zalohovani",
  "sensor.backup_posledni_pokus_o_automaticke_zalohovani",
  "sensor.sun_next_dawn",
  "sensor.sun_next_dusk",
  "sensor.sun_next_midnight",
  "sensor.sun_next_noon",
  "sensor.sun_next_rising",
  "sensor.sun_next_setting",
  "sensor.sonoff_1000af048d_temperature",
  "sensor.sonoff_1000af048d_humidity",
  "sensor.smer_vetru",
  "sensor.cerpadlo_stav",
  "sensor.cena_elektriny",
  "sensor.aktualni_tarif",
  "sensor.pro3em_total_active_energy_cost",
  "sensor.mesicni_spotreba_vt",
  "sensor.mesicni_spotreba_nt",
  "sensor.rocni_spotreba_vt",
  "sensor.rocni_spotreba_nt",
  "sensor.broadlink_rm4_mini_teplota",
  "sensor.broadlink_rm4_mini_vlhkost_vzduchu",
  "sensor.pro3em_phase_a_active_power",
  "sensor.pro3em_phase_b_active_power",
  "sensor.pro3em_phase_c_active_power",
  "sensor.pro3em_total_active_power",
  "sensor.pro3em_phase_a_apparent_power",
  "sensor.pro3em_phase_b_apparent_power",
  "sensor.pro3em_phase_c_apparent_power",
  "sensor.pro3em_total_apparent_power",
  "sensor.pro3em_phase_a_power_factor",
  "sensor.pro3em_phase_b_power_factor",
  "sensor.pro3em_phase_c_power_factor",
  "sensor.pro3em_total_active_energy",
  "sensor.pro3em_total_active_returned_energy",
  "sensor.shellypro3em_34987a685134_temperature",
  "sensor.nabijeni_napeti",
  "sensor.nabijeni_proud",
  "sensor.nabijeni_napajeni",
  "sensor.esp32_bluetooth_proxy_2ded8c",
  "sensor.bf08dduhdwfbotps_temp_current",
  "sensor.bf08dduhdwfbotps_humidity",
  "sensor.bf08dduhdwfbotps_battery_state",
  "sensor.bf08dduhdwfbotps_battery_percentage",
  "sensor.zigbee2mqtt_bridge_version",
  "sensor.tz3000_gjnozsaz_ts011f_proud",
  "sensor.tz3000_gjnozsaz_ts011f_napeti",
  "sensor.tz3000_gjnozsaz_ts011f_vykon",
  "sensor.tz3000_gjnozsaz_ts011f_souhrn_dodavky",
  "sensor.rostlina_baterie",
  "sensor.rostlina_teplota",
  "sensor.hobeian_zg_303z_rssi",
  "sensor.rostlina_vlhkost_pudy",
  "sensor.4tlacitkovy_spinac_baterie",
  "sensor.tz3000_fan_lamp_switch_ts0001_proud",
  "sensor.tz3000_fan_lamp_switch_ts0001_napeti",
  "sensor.tz3000_kqvb5akv_ts0001_lqi",
  "sensor.tz3000_fan_lamp_switch_ts0001_vykon",
  "sensor.tz3000_fan_lamp_switch_ts0001_souhrn_dodavky",
  "sensor.hobeian_zg_223z_baterie",
  "sensor.hobeian_zg_223z_osvetleni",
  "sensor.hobeian_zg_223z_rssi",
  "sensor.hobeian_zg_223z_lqi",
  "sensor.nastaveny_cas",
]

![Image](https://github.com/user-attachments/assets/68fcfd9b-dd16-4361-83ef-66082b8531b4)

**Comment by Nemnich** [comment]
Thank you very much!
